Fix bug due to change in terra's SpatExtent
rsbivand/rgrass pull request #79
Opened 2023-09-09 04:51 UTC by adamlilith

`SpatExtent` objects no longer contain the `@ptr` slot. Using `as.vector()` around a `SpatExtent` object retrieves the extent coordinates.

2023-09-09 07:12 UTC, rsbivand requested changes
Thanks. However, this needs to condition on `terra` versions. Could you please check which version brought in the change? If say 3 months ago, we could also add that version as a minimum in `DESCRIPTION`, if more recent, we need to condition. We may need to condition in code anyway for users of Windows or macOS terra binaries from CRAN for R 4.2.

2023-09-09 09:04 UTC, rsbivand commented
The slot formerly `ptr`  was renamed to `pnt` in https://github.com/rspatial/terra/commit/c2b6697aed368f17a639a5ce0e0b3d1224e8b463#diff-94c09e9a0dce65c379c47bd63c4c3fb115f0f3b516d145d1fda96458b979eebc (this is as in released 1.7-46), and to `cpp` in https://github.com/rspatial/terra/commit/c5b34dde3d1b9e98cc953c63d574289ae2e0a57e#diff-94c09e9a0dce65c379c47bd63c4c3fb115f0f3b516d145d1fda96458b979eebc. I'm a bit unsure how to proceed, since `CMD check` doesn't fail in nc_basic_spm_grass7. We'd need first to add a test that fails with 1.7-46, and then merge your PR, with further checks with 1.7-46, pre-1.7-46, and terra-master. @adamlilith what was your use case when you hit the problem? Best using nc_basic_spm_grass7.

2023-09-10 17:45 UTC, rhijmans commented
I do not think you need to condition on version. `as.vector<SpatExtent>`  has been part of terra from the first CRAN release.

The breaking code uses the `x@ptr$.....` idiom. I do not consider that a part of the user interface because I would not be able to make changes to it (e.g., adding an argument) without breaking existing code in other packages. This is why I will regularly change its name. Currently it is `x@pnt$...` on CRAN and `x@cpp$...` on github.  I warned package maintainers beforehand but this did not come up in the reverse dependency checking.

2023-09-10 18:07 UTC, rsbivand commented
@rhijmans Thanks, I understand. No revdep checks are run on examples when GRASS is absent - all the examples run with GRASS. I'll adapt and apply.

2023-09-10 18:38 UTC, rsbivand approved these changes

2023-09-10 18:38 UTC, merged

2023-09-10 19:29 UTC, rhijmans commented
Thanks. I should also have searched https://github.com/cran. Doing so today helped me find a few more cases that do not show up in reverse dependency checking.

2023-09-10 21:29 UTC, rsbivand commented
I should have looked more carefully when writing the code originally. Revised version on CRAN now.

2023-09-11 04:52 UTC, adamlilith commented
Thanks @rsbivand -- and thanks for the details on `terra`, @rhijmans, as I didn't know that about the pointer changing name.